<h3>This new page is generated by CRM/Populate/Page/Bicpopulate.php</h3>

<p>Total number of entries without BIC: {$countemptybic}. </p>

<p>Last updated entry was: </p>

<p>ID: {$currentID}, iban: {$currentIBAN}. BIC is populated with {$newbic}.</p>

